# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19ixHx4f_UfS5vyud1NPy6JDedXtFo3NA
"""

import pandas as pd
import matplotlib.pyplot as plt
from scipy.spatial.distance import euclidean, cityblock
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Dataset
data = {
    "Temp":[32,41,28,45,30],
    "Humidity":[65,30,70,20,60],
    "Wind_Speed":[12,25,10,30,15],
    "Status":["Normal","Extreme","Normal","Extreme","Normal"]
}

df = pd.DataFrame(data)

# Features and Target
X = df[["Temp","Humidity","Wind_Speed"]]
y = df["Status"]

# 1. Distance Calculation
euc = euclidean(X.iloc[0], X.iloc[1])
man = cityblock(X.iloc[0], X.iloc[1])

print("Euclidean Distance =", euc)
print("Manhattan Distance =", man)

# 2. Train KNN
model = KNeighborsClassifier(n_neighbors=3)
model.fit(X, y)

# 3. Prediction
new_day = [[39,35,22]]
prediction = model.predict(new_day)

print("Predicted Status =", prediction[0])

# 4. Accuracy
y_pred = model.predict(X)

accuracy = accuracy_score(y, y_pred)

print("Accuracy =", accuracy)

# 5. Bar Chart
plt.bar(["Euclidean","Manhattan"], [euc, man])

plt.xlabel("Distance Metric")
plt.ylabel("Distance")
plt.title("Distance Metrics Comparison")

plt.show()